from enum import StrEnum


class JoinEnum(StrEnum):
    LEFT_JOIN = 'LEFT JOIN'
    LEFT_JOIN_LATERAL = 'LEFT JOIN LATERAL'
    INNER_JOIN = 'INNER JOIN'
    INNER_JOIN_LATERAL = 'INNER JOIN LATERAL'
    CROSS_JOIN = 'CROSS JOIN'
    CROSS_JOIN_LATERAL = 'CROSS JOIN LATERAL'
